version: "2.3"

services:
    userver_project-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/userver_project/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/userver_project:rw
        ports:
          - 8080:8080
        working_dir: /userver_project
        entrypoint:
          - ./tests/run_as_user.sh
